### ISSUE TITLE
Explain rationale for using `saspy` in README FAQ section

### ISSUE THREAD

**Issue by iqis** [insightsengineering/sasr#11]
Original question: 

It looks like this package only is looking to pass code/data to and get results back from a SAS instance. Wouldn't text stream via SSH suffice? Why is involvement of a Python lib necessary?

**Comment by danielinteractive** [comment]
Thanks @iqis for the question,
indeed it is possible to just work with SSH, and actually we (and I guess many others) had an internal prototype that was working like that. 
However, after discovering `saspy` which is built by SAS itself, it seems like reinventing the wheel to come up with another interface, given that R and Python are very close to each other regarding interactive use and their home in the data science domain. The `sasr` package is a minimal solution which is extensible to interface with more `saspy` API functions as needed over time.
@clarkliming maybe it will be good to have something like this on the README page? Could be in a Q&A section.
