### ISSUE TITLE
Create a hex logo

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/sasr#12]
@BrianLang might help us here re: the approach maybe

**Comment by BrianLang** [comment]
When I made the one for MMRM I did it all from scratch using Inkscape. It seems like Alessandro did it a bit more automatically here: https://github.com/RConsortium/asa-biop-swe-wg/commit/2b94a3f03a9fea5e00615b9d72eda97d1c546849

**Comment by ellessenne** [comment]
Hi @BrianLang and @danielinteractive, yep, I created the hex sticker for the working group using the [{hexSticker}](https://cran.r-project.org/package=hexSticker) package (and a little editing with Pixelmator Pro on a Mac). If you'd like some feedback to get started, just let me know! 👍

**Comment by clarkliming** [comment]
@BrianLang could you please help create a svg here? I have no idea of this and I am totally not good at designing 🤣
