### ISSUE TITLE
Add tests that are skipped usually but can run by user once everything is set up

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/sasr#7]
Idea is that once the user has installed saspy and configured the SAS server connection, the user can run these tests to make sure that everything works:

```r
test_sasr()
```

**Comment by clarkliming** [comment]
usually `test` folder is not kept; so this `test_sasr` should be place in R folder and I think we can check the connection like

```{r}

test_sasr <- function(session) {
df2sd()
run_sas("", session = session)
}
sd2df()
```

**Comment by danielinteractive** [comment]
That would also be ok (still good to confirm that after installation of eg mmrm package from CRAN there is no tests to be run).
However it should still be granular unit level tests of the provided functions.

**Comment by clarkliming** [comment]
only if installed with `INSTALL_opts = "--install-tests"` will the tests be kept (which is not very common I think)

I think people will just call `install.packages` in most of the cases

**Comment by danielinteractive** [comment]
@clarkliming yes agree. So then let's do it in the package

**Comment by clarkliming** [comment]
as it is kind of difficult or complicated to let users to test the package after installation, will close this issue
